// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NasaImagesDemo;

namespace NasaImagesDemo.Migrations
{
    [DbContext(typeof(NasaImagesDBContext))]
    partial class NasaImagesDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NasaImagesDemo.ApodImage", b =>
                {
                    b.Property<int>("ApodImageID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("copyright")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("date")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("explanation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("hdurl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("media_type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("service_version")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApodImageID");

                    b.ToTable("ApodImages");
                });
#pragma warning restore 612, 618
        }
    }
}
